### ISSUE TITLE
LICENSE VIOLATION

### ISSUE THREAD

**Issue by 6hzw7j** [DylanHamer/MuchToolkit#3]
Please mention the LICENSE of other open source projects used.
[Coinmarket license.](https://github.com/mrsmn/coinmarketcap-api/blob/master/LICENSE)
The owner of the Coinmarket python API Git, can be found @mrsmn

This message is posted from the pov of a open source member.

**Comment by DylanHamer** [comment]
Oh crap! I forgot! Sorry. I'll append the license when I have time.

**Comment by DylanHamer** [comment]
Fixed! Added a 'licenses' command to view open source licenses.
